#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2023-2026 Andrew Gunnerson
# SPDX-License-Identifier: GPL-3.0-only

from collections.abc import Callable, Iterable
import dataclasses
import hashlib
import io
import os
import subprocess
import sys
import tempfile
import urllib.request
import xml.etree.ElementTree as ET

GOOGLE_MAVEN_REPO = 'https://dl.google.com/android/maven2'


def add_source_exclusions(ns: str, root: ET.Element):
    configuration = root.find(f'{{{ns}}}configuration')
    if configuration is None:
        raise ValueError('<configuration> tag not found')

    trusted_artifacts = ET.SubElement(
        configuration, f'{{{ns}}}trusted-artifacts')

    for regex in [
        r'.*-javadoc[.]jar',
        r'.*-sources[.]jar',
        r'.*-src[.]zip',
    ]:
        ET.SubElement(trusted_artifacts, f'{{{ns}}}trust', attrib={
            'file': regex,
            'regex': 'true',
        })


@dataclasses.dataclass
class ArtifactInfo:
    group: str
    name: str
    version: str


@dataclasses.dataclass
class ArtifactAssets:
    repo: str
    files: list[str]


def add_missing_components(
    ns: str,
    root: ET.Element,
    name: str,
    assets_for: Callable[[ArtifactInfo], ArtifactAssets],
):
    components = root.find(f'{{{ns}}}components')
    if components is None:
        raise ValueError('<components> tag not found')

    component = components.find(f'{{{ns}}}component[@name="{name}"]')
    if component is None:
        raise ValueError(f'<component name="{name}"> tag not found')

    info = ArtifactInfo(
        group=component.attrib['group'],
        name=component.attrib['name'],
        version=component.attrib['version'],
    )
    assets = assets_for(info)

    for filename in assets.files:
        if component.find(f'{{{ns}}}artifact[@name="{filename}"]') is not None:
            continue

        path = f'{info.group.replace(".", "/")}/{name}/{info.version}/{filename}'
        url = f'{assets.repo}/{path}'

        try:
            with urllib.request.urlopen(url) as r:
                digest = hashlib.file_digest(r, 'sha512')
        except urllib.request.HTTPError as e:
            raise Exception(f'Failed to download: {e.url}') from e

        artifact = ET.SubElement(component, f'{{{ns}}}artifact',
                                 attrib={'name': filename})

        ET.SubElement(artifact, f'{{{ns}}}sha512', attrib={
            'value': digest.hexdigest(),
            'origin': 'Generated by Gradle',
        })

    component[:] = sorted(component, key=lambda child: child.attrib['name'])


def add_missing_aapt2_platforms(ns: str, root: ET.Element):
    platforms = ['linux', 'osx', 'windows']

    add_missing_components(
        ns,
        root,
        'aapt2',
        lambda info: ArtifactAssets(
            repo=GOOGLE_MAVEN_REPO,
            files=[f'{info.name}-{info.version}-{p}.jar' for p in platforms],
        ),
    )


def patch_xml(path: str | os.PathLike[str]):
    tree = ET.parse(path)
    root = tree.getroot()

    ns = 'https://schema.gradle.org/dependency-verification'
    ET.register_namespace('', ns)

    # Add exclusions to allow Android Studio to download sources.
    add_source_exclusions(ns, root)

    # Gradle only adds entries for the host OS. We have to manually add the
    # checksums for the other major desktop OSs.
    add_missing_aapt2_platforms(ns, root)

    # Match gradle's formatting exactly.
    ET.indent(tree, '   ')
    root.tail = '\n'

    with io.BytesIO() as f:
        # etree's xml_declaration=True uses single quotes in the header.
        f.write(b'<?xml version="1.0" encoding="UTF-8"?>\n')
        tree.write(f)
        serialized = f.getvalue().replace(b' />', b'/>')

    with open(path, 'wb') as f:
        f.write(serialized)


def main():
    root_dir = os.path.join(sys.path[0], '..')
    xml_file = os.path.join(sys.path[0], 'verification-metadata.xml')

    try:
        os.remove(xml_file)
    except FileNotFoundError:
        pass

    # Gradle will sometimes fail to add verification entries for artifacts that
    # are already cached.
    with tempfile.TemporaryDirectory() as temp_dir:
        env = os.environ | {'GRADLE_USER_HOME': temp_dir}

        subprocess.check_call(
            [
                './gradlew' + ('.bat' if os.name == 'nt' else ''),
                '--write-verification-metadata', 'sha512',
                '--no-daemon',
                'build',
                'zipDebug',
                # Requires signing.
                '-x', 'assembleRelease',
            ],
            env=env,
            cwd=root_dir,
        )

    patch_xml(xml_file)


if __name__ == '__main__':
    main()
