#!/sbin/sh

OUTFD=${2}
ZIPFILE=${3}

umask 022

ui_print() {
    printf "ui_print %s\nui_print\n" "${*}" > /proc/self/fd/"${OUTFD}"
}

if [ -f /sbin/recovery ] || [ -f /system/bin/recovery ]; then
    # Installing via recovery. Always do a direct install.
    set -exu

    ui_print 'Mounting system'
    if mount /system_root; then
        mount -o remount,rw /system_root
        root_dir=/system_root
    else
        mount /system
        mount -o remount,rw /system
        root_dir=/
    fi

    ui_print 'Extracting files'

    # Just overwriting isn't sufficient because the apk filenames are different
    # between debug and release builds
    app_id=$(unzip -p "${ZIPFILE}" module.prop | grep '^id=' | cut -d= -f2)

    # rm on some custom recoveries doesn't exit with 0 on ENOENT, even with -f
    rm -rf "${root_dir}/system/priv-app/${app_id}" || :

    unzip -o "${ZIPFILE}" 'system/*' -d "${root_dir}"

    ui_print 'Done!'
else
    # Installing via Magisk Manager.

    . /data/adb/magisk/util_functions.sh

    install_module
fi
